### ISSUE TITLE
Create Wall

### ISSUE THREAD

**Issue by benbjamin123** [ColtonGarelli/Architecture-Advisor3000#13]
Interior+Exterior walls should be treated separately

**Comment by ColtonGarelli** [comment]
Done when: changes can be made (i.e. add window) and changes should be reflected post update (the wall updates with new association with window).

**Comment by ColtonGarelli** [comment]
Interior+exterior walls? or just walls with interior+exterior features. Orientation? Labels for each wall (counterclockwise/clockwise). Is wall an object or a set of features in the building class. if so, features list, or explicitly define (window1, window2, door)...probably list of features that can change size depending on size of wall?

**Comment by agable74** [comment]
Have x and y coordinate system for wall base corners. Origin point at the first corner of the wall

**Comment by ColtonGarelli** [comment]
revisited at 7:15

**Comment by ColtonGarelli** [comment]
forgot to update last night.  Worked until 8:30 (I had a meeting then).  worked from 8:20-9 today.
