### ISSUE TITLE
Display Available Materials

### ISSUE THREAD

**Issue by benbjamin123** [ColtonGarelli/Architecture-Advisor3000#21]
Done when can print a list of materials we can use

**Comment by agable74** [comment]
Uses #26 toString to print out all of the available materials in a list with columns

**Comment by benbjamin123** [comment]
I am trying to call the toString function of a MaterialByArea object, but it is causing an error. The error message is "Non-static method 'toString()' cannot be referenced in a static context".

**Comment by benbjamin123** [comment]
Added test for displaying materialByArea objects, and began implementing functionality. Hours: 1
