### ISSUE TITLE
Create Wall

### ISSUE THREAD

**Issue by agable74** [ColtonGarelli/Architecture-Advisor3000#25]
Create basic interior wall.

Done when a wall can be created on the interior of a structure.
The user MUST be able to create a wall from the UI.
Used to calculate building cost estimate.

Allows doors but not windows

**Comment by ColtonGarelli** [comment]
Worked from 6:30-8.

**Comment by benbjamin123** [comment]
Added area and cost calculations to wall, and total cost calculations to building. Hours: 1.5

**Comment by benbjamin123** [comment]
Stuck on UI - The current implementation of the UI makes writing tests difficult

**Comment by benbjamin123** [comment]
Added UI addWall function. Hours: 1
