### ISSUE TITLE
Create List of Building Materials

### ISSUE THREAD

**Issue by benbjamin123** [ColtonGarelli/Architecture-Advisor3000#26]
Done when a list of materials is created, each associated with a unit quantity and a price.

**Comment by benbjamin123** [comment]
Done when a list of materials is created, each associated with a unit quantity and a price.

**Comment by agable74** [comment]
Created materials class and tested it in 2 hours. Not done yet

**Comment by agable74** [comment]
Need to add in actual list of building materials and prices from Home Depot or Lowe's

**Comment by agable74** [comment]
added some basic materials

**Comment by agable74** [comment]
Will need to add more material extensions later for more options of building materials

**Comment by agable74** [comment]
Ended up taking about 5 hours
