### ISSUE TITLE
Add+remove features to Wall (window, door, etc)

### ISSUE THREAD

**Issue by ColtonGarelli** [ColtonGarelli/Architecture-Advisor3000#35]
DW:

**Comment by danny97101** [comment]
Done When: The system has the capability to remove a wall from a structure, affecting its price, etc.

**Comment by agable74** [comment]
@danny97101 That done when should be a separate card, this one is for adding features to walls.

Done when: A window and/or a wall can be added/removed from a particular wall.

**Comment by agable74** [comment]
Will require the UI to handle the index for removing/getting features

**Comment by agable74** [comment]
Took me 0.5 hours since some of it was already done.
