### ISSUE TITLE
Basic User Interface

### ISSUE THREAD

**Issue by agable74** [ColtonGarelli/Architecture-Advisor3000#39]
Done when user can interact with system

**Comment by agable74** [comment]
Done when we can interactively do everything due this sprint. Everything completed for this sprint needs to be demonstrable

**Comment by agable74** [comment]
Tested + implemented a function that checks if a user input is yes or no (.5hr)

**Comment by agable74** [comment]
Relies on #42

**Comment by agable74** [comment]
Added function + cleaned up some, added ability to set and get walls from a building 0.5hr

**Comment by ColtonGarelli** [comment]
3 hours total (2.5 from me)
