### ISSUE TITLE
Error Handling UI

### ISSUE THREAD

**Issue by agable74** [ColtonGarelli/Architecture-Advisor3000#56]
DW: UI handles errors including type + proper range of numbers

**Comment by ColtonGarelli** [comment]
I think i covered our bases with proper range by using switch-case with a default (if int != to any defined cases) and have handling to catch type errors.

**Comment by ColtonGarelli** [comment]
1.5 hours

**Comment by ColtonGarelli** [comment]
Change next() to nextlines()

**Comment by agable74** [comment]
Change next() to nextline() and change continue asking to a number 1-6
