### ISSUE TITLE
Architect Login

### ISSUE THREAD

**Issue by agable74** [ColtonGarelli/Architecture-Advisor3000#59]
Done when: Architect can view architect mode to design houses

**Comment by agable74** [comment]
Works in tandem with #58

**Comment by benbjamin123** [comment]
Added login and architect function to the  UI. Hours : 2.5

**Comment by benbjamin123** [comment]
Stuck: In addWallFeature function, the size of the walls collection in the inputted building keeps coming back as 0.

**Comment by benbjamin123** [comment]
Added removeWallFeature function and some other menu elements. Hours: 1

**Comment by agable74** [comment]
Put in IO for Architect 0.5hr

**Comment by agable74** [comment]
Altered the UI so that you can do the things from the backend. 1hr.
