### ISSUE TITLE
Multiple Floor Capability

### ISSUE THREAD

**Issue by agable74** [ColtonGarelli/Architecture-Advisor3000#60]
Done when you can add floors and do everything you could on the lower floors on the upper floors. Also ability to construct a building starting off with multiple floors, asking user for amount of floors and the dimensions of the walls.

**Comment by benbjamin123** [comment]
Building could have a floor array

**Comment by ColtonGarelli** [comment]
3 hrs

**Comment by agable74** [comment]
0.5 hours to fit in the fileIO
