### ISSUE TITLE
File Output

### ISSUE THREAD

**Issue by martypv** [ColtonGarelli/Architecture-Advisor3000#7]
Done when you can save the program data to the file.

Dependent on #22

**Comment by groth12** [comment]
Does this include cloud storage or only local storage

**Comment by benbjamin123** [comment]
This card includes only local storage. Cloud storage implementation is further down in the priority list.

**Comment by agable74** [comment]
Worked .5 hours, not going to do for sprint, others more important

**Comment by agable74** [comment]
Had to add a few things to building constructor, will need to add more toStrings to get to work. 1 hr

**Comment by agable74** [comment]
Got the file output working. Will need a new file name for each building, which makes the most sense when thinking of sending the building info. It would take me much longer to get the appending correct for having multiple on one file. 1 hr

**Comment by agable74** [comment]
Total 3 hour for this sprint
