### ISSUE TITLE
Create a structure

### ISSUE THREAD

**Issue by ColtonGarelli** [ColtonGarelli/Architecture-Advisor3000#8]

**Comment by ColtonGarelli** [comment]
Relies on: #13, #14, #19, #17

**Comment by benbjamin123** [comment]
Structure is a bad word for this - we should just call it Building

**Comment by benbjamin123** [comment]
Added tests and implementation functions, 2 hours

**Comment by benbjamin123** [comment]
Added costByUnit functionality, 1 hour. Should we just measure everything in meters?
